export const actionTypes = {
  SET_USERS: 'SET_USERS',
  SET_SESSIONS: 'SET_SESSIONS',
  SET_SELECTED_SESSION: 'SET_SELECTED_SESSION',
  SET_SELECTED_USER: 'SET_SELECTED_USER',
  SET_VIEW: 'SET_VIEW',
  SET_SELECTED_SESSION_EVENT: 'SET_SELECTED_SESSION_EVENT'
};
